version: '3.7'
services:
  database:
    image: 'postgres:11'
    container_name: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: 'valhalla'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - "5432"
  redis:
    image: 'redis:3.0-alpine'
    container_name: redis
    restart: on-failure
    ports:
      - "6379"

  web:
    container_name: cashvalue-backend
    build:
      context: .
    volumes:
      - ".:/opt/app" 
    command: ./prod-start.sh
    env_file: .env
    ports:
      - "8000:8000"
    depends_on: 
      - database
      - redis
  
  worker:
  #container_name: cashvalue-worker
    build: .
    restart: on-failure
    env_file: .env
    command: ./prod-start.sh
    volumes:
      - ".:/opt/app"

volumes:
  database-data:

