"""reafctored transactions table

Revision ID: 03a8c4c23b10
Revises: b25f559b8f65
Create Date: 2017-11-14 12:14:20.938417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03a8c4c23b10'
down_revision = 'b25f559b8f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_cost', sa.Float(), nullable=True))
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'meta')
    op.drop_column('transactions', 'reference_id')
    op.drop_column('transactions', 'transaction_id')
    op.drop_column('transactions', 'fees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('reference_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('meta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'transaction_cost')
    op.drop_column('transactions', 'timestamp')
    # ### end Alembic commands ###
