"""
Added Campaign relation


Revision ID: 06f93671813b
Revises: 351cc27cfdba
Create Date: 2017-12-28 21:48:15.408232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06f93671813b'
down_revision = '351cc27cfdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscribers_phoneNumber', 'subscribers', ['phoneNumber'], unique=False)
    op.drop_index(op.f('ix_subscribers_phoneNumber'), table_name='subscribers')
    op.drop_constraint(None, 'choices', type_='foreignkey')
    op.create_foreign_key(u'choices_campaign_id_fkey', 'choices', 'campaigns', ['campaign_id'], ['id'])
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'campaigns_pkey')
    )
    op.drop_index(op.f('ix_sms_campaigns_title'), table_name='sms_campaigns')
    op.drop_index(op.f('ix_sms_campaigns_timestamp'), table_name='sms_campaigns')
    op.drop_index(op.f('ix_sms_campaigns_id'), table_name='sms_campaigns')
    op.drop_table('sms_campaigns')
    # ### end Alembic commands ###
