"""empty message

Revision ID: 0edb650457ff
Revises: 9c8795622053
Create Date: 2017-06-27 16:32:33.625000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edb650457ff'
down_revision = '9c8795622053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_holder')
    op.add_column('tickets', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'events', ['event_id'], ['id'])
    op.add_column('users', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'ticket_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'event_id')
    op.create_table('ticket_holder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('holder_id', sa.INTEGER(), nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['holder_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
