"""empty message

Revision ID: 1457d471ad04
Revises: 62cc3cb59048
Create Date: 2017-12-28 10:32:11.354479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1457d471ad04'
down_revision = '62cc3cb59048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('susbscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['susbscription_id'], [u'subscriptions.id'], name=u'sms_logs_susbscription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'sms_logs_pkey')
    )
    # ### end Alembic commands ###
