"""empty message

Revision ID: 159b0e16d24d
Revises: 4904b152b0f5
Create Date: 2017-09-21 01:24:56.258822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159b0e16d24d'
down_revision = '4904b152b0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('filename', sa.String(), nullable=True))
    op.drop_column('events', 'logo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('logo_url', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('events', 'filename')
    # ### end Alembic commands ###
