"""empty message

Revision ID: 2d23a32286a7
Revises: 348704afef24
Create Date: 2017-08-03 00:04:28.236142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d23a32286a7'
down_revision = '348704afef24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('currency_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'currency_code')
    # ### end Alembic commands ###
