"""empty message

Revision ID: 2e121af25707
Revises: fcbf851e2ff9
Create Date: 2017-12-28 23:24:37.319307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e121af25707'
down_revision = 'fcbf851e2ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('phone_number', sa.String(length=14), nullable=False))
    op.create_index(op.f('ix_subscribers_phone_number'), 'subscribers', ['phone_number'], unique=False)
    op.drop_index('ix_subscribers_phoneNumber', table_name='subscribers')
    op.drop_column('subscribers', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('phoneNumber', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.create_index('ix_subscribers_phoneNumber', 'subscribers', ['phoneNumber'], unique=False)
    op.drop_index(op.f('ix_subscribers_phone_number'), table_name='subscribers')
    op.drop_column('subscribers', 'phone_number')
    # ### end Alembic commands ###
