"""empty message

Revision ID: 611fc3f13b14
Revises: db6fb5278fbd
Create Date: 2017-11-21 02:57:46.665812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611fc3f13b14'
down_revision = 'db6fb5278fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['title'])
    op.drop_column('subscriptions', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('name', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
