"""empty message

Revision ID: 6a403f957c70
Revises: 2f4eca86137d
Create Date: 2017-08-15 14:21:21.341427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a403f957c70'
down_revision = '2f4eca86137d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venue', sa.String(length=64), nullable=True))
    op.drop_index('ix_users_phone', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=1)
    op.drop_column('events', 'venue')
    # ### end Alembic commands ###
