"""empty message

Revision ID: 6c8dede0eaaa
Revises: b255d3002924
Create Date: 2017-12-29 13:48:43.959417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8dede0eaaa'
down_revision = 'b255d3002924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'timestamp')
    # ### end Alembic commands ###
