"""reafctored transactions table

Revision ID: 742b57fea6cd
Revises: 03a8c4c23b10
Create Date: 2017-11-14 12:34:44.991444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742b57fea6cd'
down_revision = '03a8c4c23b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('transactions', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
