"""empty message

Revision ID: 7c6279aff059
Revises: 06f93671813b
Create Date: 2017-12-28 21:51:15.439265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6279aff059'
down_revision = '06f93671813b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_subscribers_phoneNumber'), 'subscribers', ['phoneNumber'], unique=False)
    # op.drop_index('ix_subscribers_phoneNumber', table_name='subscribers')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscribers_phoneNumber', 'subscribers', ['phoneNumber'], unique=False)
    op.drop_index(op.f('ix_subscribers_phoneNumber'), table_name='subscribers')
    # ### end Alembic commands ###
