"""empty message

Revision ID: 7e9518a4c59d
Revises: 8df385b3b425
Create Date: 2017-11-07 13:19:54.181960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9518a4c59d'
down_revision = '8df385b3b425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('location', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'location')
    # ### end Alembic commands ###
