"""empty message

Revision ID: 81b7dfb8ba0c
Revises: b1add8e1a701
Create Date: 2017-11-14 19:26:30.285111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b7dfb8ba0c'
down_revision = 'b1add8e1a701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('request_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
