"""empty message

Revision ID: 9934fb768805
Revises: 159b0e16d24d
Create Date: 2017-10-23 23:38:14.125508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9934fb768805'
down_revision = '159b0e16d24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('url', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
