"""empty message

Revision ID: 9cb122a9f203
Revises: 7c6279aff059
Create Date: 2017-12-28 21:51:51.549686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb122a9f203'
down_revision = '7c6279aff059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_subscribers_phoneNumber'), 'subscribers', ['phoneNumber'], unique=False)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_phoneNumber'), table_name='subscribers')
    # ### end Alembic commands ###
