"""empty message

Revision ID: 9fa7413a2eaa
Revises: 7e9518a4c59d
Create Date: 2017-11-07 13:53:19.016580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa7413a2eaa'
down_revision = '7e9518a4c59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'code',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(u'tickets_code_key', 'tickets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'tickets_code_key', 'tickets', ['code'])
    op.alter_column('tickets', 'code',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
