"""empty message

Revision ID: a1a2f6c2dc9b
Revises: 3dd8a72e1a2b
Create Date: 2017-10-31 18:02:37.813021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a2f6c2dc9b'
down_revision = '3dd8a72e1a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'timestamp')
    # ### end Alembic commands ###
