"""Added request_id field to transaction table

Revision ID: b1add8e1a701
Revises: 742b57fea6cd
Create Date: 2017-11-14 18:36:58.809457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1add8e1a701'
down_revision = '742b57fea6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('request_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'request_id')
    # ### end Alembic commands ###
