"""empty message

Revision ID: c634475525d2
Revises: 9cb122a9f203
Create Date: 2017-12-28 21:52:00.119872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c634475525d2'
down_revision = '9cb122a9f203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribers_phoneNumber', table_name='subscribers')
    op.create_index(op.f('ix_subscribers_phoneNumber'), 'subscribers', ['phoneNumber'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscribers_phoneNumber', 'subscribers', ['phoneNumber'], unique=False)
    op.drop_index(op.f('ix_subscribers_phoneNumber'), table_name='subscribers')
    # ### end Alembic commands ###
