"""empty message

Revision ID: c6894ebbdcea
Revises: c634475525d2
Create Date: 2017-12-28 21:54:11.780569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6894ebbdcea'
down_revision = 'c634475525d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_subscribers_phoneNumber'), 'subscribers', ['phoneNumber'], unique=False)
    # op.drop_index('ix_subscribers_phoneNumber', table_name='subscribers')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscribers_phoneNumber', 'subscribers', ['phoneNumber'], unique=False)
    op.drop_index(op.f('ix_subscribers_phoneNumber'), table_name='subscribers')
    # ### end Alembic commands ###
