"""empty message

Revision ID: d076b0d5e802
Revises: 1457d471ad04
Create Date: 2017-12-28 11:53:48.940821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd076b0d5e802'
down_revision = '1457d471ad04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.DateTime(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('sucess_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
