"""empty message

Revision ID: e5f1ee70ba9b
Revises: a654e00718f8
Create Date: 2017-08-27 23:16:53.316116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f1ee70ba9b'
down_revision = 'a654e00718f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('accounts', 'points')
    # ### end Alembic commands ###
